import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { Workbook } from 'exceljs';
import type { User } from '@prisma/client';
import { PrismaService } from '../../../prisma/prisma.service';
import { CryptoService } from '../../../common/services/crypto.service';
import { AuditService } from '../../../common/services/audit.service';
import { ToolContext } from '../tools/tool.types';

export interface ReportSpec {
  format: 'pdf' | 'xlsx' | 'csv';
  fileName: string; // base name, no extension
  title: string;
  subtitle?: string;
  columns: { key: string; header: string }[];
  rows: Record<string, unknown>[];
}

function normalize(v: unknown): string | number {
  if (v == null) return '';
  if (typeof v === 'number') return v;
  return String(v);
}

function csvCell(v: unknown): string {
  const s = v == null ? '' : String(v);
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function pdfBuffer(spec: ReportSpec): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 36,
      size: 'A4',
      layout: spec.columns.length > 5 ? 'landscape' : 'portrait',
    });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject); // pdfkit must never hang the request
    doc.fontSize(15).text(spec.title);
    if (spec.subtitle) doc.moveDown(0.3).fontSize(9).fillColor('#555').text(spec.subtitle);
    doc.moveDown(0.6).fillColor('#000');
    doc.fontSize(8).text(spec.columns.map((c) => c.header).join('   |   '));
    doc.moveTo(36, doc.y + 1).lineTo(doc.page.width - 36, doc.y + 1).stroke();
    doc.moveDown(0.3);
    for (const r of spec.rows) {
      doc.fontSize(8).text(spec.columns.map((c) => String(normalize(r[c.key]))).join('   |   '));
    }
    doc.moveDown(1).fontSize(7).fillColor('#888').text(`Generated by IRIS · ${spec.rows.length} rows · CONFIDENTIAL — NTAA §139`);
    doc.end();
  });
}

/**
 * Renders a report to PDF / Excel / CSV, then ENCRYPTS the artifact with the
 * platform CryptoService (AES-256-GCM) before it touches the DB. Download
 * re-checks ownership, decrypts server-side, and audits every export/download —
 * so a report file never exists on disk in the clear.
 */
@Injectable()
export class ExportService {
  constructor(
    private prisma: PrismaService,
    private crypto: CryptoService,
    private audit: AuditService,
  ) {}

  private async render(spec: ReportSpec): Promise<{ buffer: Buffer; mimeType: string; ext: string }> {
    if (spec.format === 'csv') {
      const header = spec.columns.map((c) => csvCell(c.header)).join(',');
      const lines = spec.rows.map((r) => spec.columns.map((c) => csvCell(r[c.key])).join(','));
      return { buffer: Buffer.from([header, ...lines].join('\r\n'), 'utf8'), mimeType: 'text/csv', ext: 'csv' };
    }
    if (spec.format === 'xlsx') {
      const wb = new Workbook();
      const ws = wb.addWorksheet('Report');
      ws.addRow([spec.title]);
      if (spec.subtitle) ws.addRow([spec.subtitle]);
      ws.addRow(spec.columns.map((c) => c.header));
      for (const r of spec.rows) ws.addRow(spec.columns.map((c) => normalize(r[c.key])));
      const buf = (await wb.xlsx.writeBuffer()) as unknown as Buffer;
      return { buffer: buf, mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', ext: 'xlsx' };
    }
    return { buffer: await pdfBuffer(spec), mimeType: 'application/pdf', ext: 'pdf' };
  }

  async generate(ctx: ToolContext, spec: ReportSpec): Promise<{ exportId: string; fileName: string; mimeType: string; sizeBytes: number; rowCount: number }> {
    const { buffer, mimeType, ext } = await this.render(spec);
    const fileName = `${spec.fileName}.${ext}`;
    const cipher = this.crypto.encrypt(buffer.toString('base64'));
    if (!cipher) throw new Error('Failed to encrypt export.');

    const row = await this.prisma.irisExport.create({
      data: { staffId: ctx.staff.id, fileName, format: spec.format, mimeType, sizeBytes: buffer.length, cipher },
    });
    await this.audit.log({
      actorType: 'STAFF', actorId: ctx.staff.id, staffId: ctx.staff.id,
      action: 'IRIS_EXPORT_CREATE', entity: 'IrisExport', entityId: row.id,
      afterJson: { fileName, format: spec.format, rows: spec.rows.length },
    });
    return { exportId: row.id, fileName, mimeType, sizeBytes: buffer.length, rowCount: spec.rows.length };
  }

  async download(exportId: string, staff: User): Promise<{ fileName: string; mimeType: string; buffer: Buffer }> {
    const row = await this.prisma.irisExport.findUnique({ where: { id: exportId } });
    if (!row) throw new NotFoundException('Export not found.');
    if (row.staffId !== staff.id) throw new ForbiddenException('This export belongs to another officer.');
    const b64 = this.crypto.decrypt(row.cipher);
    if (!b64) throw new Error('Failed to decrypt export.');
    await this.prisma.irisExport.update({ where: { id: exportId }, data: { downloadedAt: new Date() } });
    await this.audit.log({
      actorType: 'STAFF', actorId: staff.id, staffId: staff.id,
      action: 'IRIS_EXPORT_DOWNLOAD', entity: 'IrisExport', entityId: exportId,
    });
    return { fileName: row.fileName, mimeType: row.mimeType, buffer: Buffer.from(b64, 'base64') };
  }
}
