import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { Workbook } from 'exceljs';
import type { User } from '@prisma/client';
import { PrismaService } from '../../../prisma/prisma.service';
import { CryptoService } from '../../../common/services/crypto.service';
import { AuditService } from '../../../common/services/audit.service';
import { ToolContext } from '../tools/tool.types';
import { buildExcelWatermarkPng } from '../../../common/services/excel-watermark';

export interface ReportSpec {
  format: 'pdf' | 'xlsx' | 'csv';
  fileName: string; // base name, no extension
  title: string;
  subtitle?: string;
  columns: { key: string; header: string }[];
  rows: Record<string, unknown>[];
}

function normalize(v: unknown): string | number {
  if (v == null) return '';
  if (typeof v === 'number') return v;
  return String(v);
}

function csvCell(v: unknown): string {
  const s = v == null ? '' : String(v);
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

const TEAL = '#0f766e';

function pdfBuffer(spec: ReportSpec, watermark: { orgShort: string; officerName: string }): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 40,
      size: 'A4',
      layout: spec.columns.length > 5 ? 'landscape' : 'portrait',
    });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject); // pdfkit must never hang the request

    const left = doc.page.margins.left;
    const usable = doc.page.width - doc.page.margins.left - doc.page.margins.right;

    // Letterhead
    doc.rect(left, doc.y, usable, 3).fill(TEAL);
    doc.moveDown(0.5).fillColor(TEAL).font('Helvetica-Bold').fontSize(9).text('BIZDATA · Revenue Intelligence', left);
    doc.fillColor('#000').font('Helvetica-Bold').fontSize(15).text(spec.title);
    if (spec.subtitle) doc.font('Helvetica').fontSize(9).fillColor('#555').text(spec.subtitle);
    doc.fillColor('#b91c1c').font('Helvetica-Bold').fontSize(7)
      .text(`CONFIDENTIAL — ${watermark.orgShort} — Generated by ${watermark.officerName} · NTAA §139. Do not distribute.`);
    doc.moveDown(0.5).fillColor('#000');

    const n = spec.columns.length;
    const colW = usable / n;
    const rowH = 15;
    const headerH = 18;

    const drawHeader = () => {
      const y = doc.y;
      doc.rect(left, y, usable, headerH).fill(TEAL);
      doc.fillColor('#fff').font('Helvetica-Bold').fontSize(7);
      spec.columns.forEach((c, i) => doc.text(c.header, left + i * colW + 3, y + 5, { width: colW - 6, ellipsis: true }));
      doc.y = y + headerH;
      doc.fillColor('#000').font('Helvetica').fontSize(7);
    };
    drawHeader();

    spec.rows.forEach((r, idx) => {
      if (doc.y + rowH > doc.page.height - doc.page.margins.bottom) {
        doc.addPage();
        drawHeader();
      }
      const y = doc.y;
      if (idx % 2 === 1) doc.rect(left, y, usable, rowH).fill('#f1f5f9');
      doc.fillColor('#111').font('Helvetica').fontSize(7);
      spec.columns.forEach((c, i) =>
        doc.text(String(normalize(r[c.key])), left + i * colW + 3, y + 4, { width: colW - 6, ellipsis: true }),
      );
      doc.y = y + rowH;
    });

    doc.moveDown(0.8).font('Helvetica').fontSize(7).fillColor('#888')
      .text(`Generated by ${watermark.officerName} via IRIS · ${spec.rows.length} rows · ${new Date().toISOString().slice(0, 10)}`, left);
    doc.end();
  });
}

/**
 * Renders a report to PDF / Excel / CSV, then ENCRYPTS the artifact with the
 * platform CryptoService (AES-256-GCM) before it touches the DB. Download
 * re-checks ownership, decrypts server-side, and audits every export/download —
 * so a report file never exists on disk in the clear.
 */
@Injectable()
export class ExportService {
  constructor(
    private prisma: PrismaService,
    private crypto: CryptoService,
    private audit: AuditService,
  ) {}

  private async render(
    spec: ReportSpec,
    watermark: { orgShort: string; officerName: string },
  ): Promise<{ buffer: Buffer; mimeType: string; ext: string }> {
    if (spec.format === 'csv') {
      const header = spec.columns.map((c) => csvCell(c.header)).join(',');
      const lines = spec.rows.map((r) => spec.columns.map((c) => csvCell(r[c.key])).join(','));
      return { buffer: Buffer.from([header, ...lines].join('\r\n'), 'utf8'), mimeType: 'text/csv', ext: 'csv' };
    }
    if (spec.format === 'xlsx') {
      const wb = new Workbook();
      const ws = wb.addWorksheet('Report');

      // Native worksheet background (Page Layout > Background) — Excel tiles
      // this automatically across the whole sheet, in every direction, in
      // Normal view too, not just print. A one-sided banner row can be
      // scrolled past, deleted, or cropped out of a screenshot; this can't.
      const wmPng = await buildExcelWatermarkPng(watermark.orgShort, watermark.officerName);
      const imageId = wb.addImage({ buffer: wmPng as any, extension: 'png' });
      ws.addBackgroundImage(imageId);

      const confRow = ws.addRow([`CONFIDENTIAL — ${watermark.orgShort} — Generated by ${watermark.officerName} · ${new Date().toISOString()}`]);
      confRow.font = { bold: true, color: { argb: 'FFB91C1C' } };
      ws.mergeCells(confRow.number, 1, confRow.number, Math.max(spec.columns.length, 1));

      ws.addRow([spec.title]).font = { bold: true, size: 14 };
      if (spec.subtitle) ws.addRow([spec.subtitle]);
      const headerRow = ws.addRow(spec.columns.map((c) => c.header));
      headerRow.font = { bold: true };
      for (const r of spec.rows) ws.addRow(spec.columns.map((c) => normalize(r[c.key])));
      const buf = (await wb.xlsx.writeBuffer()) as unknown as Buffer;
      return { buffer: buf, mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', ext: 'xlsx' };
    }
    return { buffer: await pdfBuffer(spec, watermark), mimeType: 'application/pdf', ext: 'pdf' };
  }

  async generate(ctx: ToolContext, spec: ReportSpec): Promise<{ exportId: string; fileName: string; mimeType: string; sizeBytes: number; rowCount: number }> {
    const tenant = await this.prisma.tenant.findFirst({ select: { shortName: true } });
    const watermark = {
      orgShort: tenant?.shortName || 'IRS',
      officerName: [ctx.staff.firstName, ctx.staff.lastName].filter(Boolean).join(' ') || ctx.staff.email || ctx.staff.id,
    };
    const { buffer, mimeType, ext } = await this.render(spec, watermark);
    const fileName = `${spec.fileName}.${ext}`;
    const cipher = this.crypto.encrypt(buffer.toString('base64'));
    if (!cipher) throw new Error('Failed to encrypt export.');

    const row = await this.prisma.irisExport.create({
      data: { staffId: ctx.staff.id, fileName, format: spec.format, mimeType, sizeBytes: buffer.length, cipher },
    });
    await this.audit.log({
      actorType: 'STAFF', actorId: ctx.staff.id, staffId: ctx.staff.id,
      action: 'IRIS_EXPORT_CREATE', entity: 'IrisExport', entityId: row.id,
      afterJson: { fileName, format: spec.format, rows: spec.rows.length },
    });
    return { exportId: row.id, fileName, mimeType, sizeBytes: buffer.length, rowCount: spec.rows.length };
  }

  /**
   * Same watermarked-background xlsx as `render`, but for a document that is
   * naturally more than one table (the tax report: income, tax cards,
   * provider transactions, signals, cases) — one worksheet per table rather
   * than forcing them into one flat sheet.
   */
  async renderMultiSheetXlsx(
    staff: { id: string; email?: string | null; firstName?: string | null; lastName?: string | null },
    input: { fileName: string; sheets: { name: string; title: string; columns: { key: string; header: string }[]; rows: Record<string, unknown>[] }[] },
  ): Promise<{ fileName: string; mimeType: string; buffer: Buffer }> {
    const tenant = await this.prisma.tenant.findFirst({ select: { shortName: true } });
    const orgShort = tenant?.shortName || 'IRS';
    const officerName = [staff.firstName, staff.lastName].filter(Boolean).join(' ') || staff.email || staff.id;
    const wmPng = await buildExcelWatermarkPng(orgShort, officerName);

    const wb = new Workbook();
    const imageId = wb.addImage({ buffer: wmPng as any, extension: 'png' });
    for (const sheet of input.sheets) {
      const ws = wb.addWorksheet(sheet.name.slice(0, 31)); // Excel's sheet-name length limit
      ws.addBackgroundImage(imageId);
      const confRow = ws.addRow([`CONFIDENTIAL — ${orgShort} — Generated by ${officerName} · ${new Date().toISOString()}`]);
      confRow.font = { bold: true, color: { argb: 'FFB91C1C' } };
      ws.mergeCells(confRow.number, 1, confRow.number, Math.max(sheet.columns.length, 1));
      ws.addRow([sheet.title]).font = { bold: true, size: 14 };
      const headerRow = ws.addRow(sheet.columns.map((c) => c.header));
      headerRow.font = { bold: true };
      for (const r of sheet.rows) ws.addRow(sheet.columns.map((c) => normalize(r[c.key])));
    }
    const buffer = (await wb.xlsx.writeBuffer()) as unknown as Buffer;
    const fileName = `${input.fileName}.xlsx`;

    await this.audit.log({
      actorType: 'STAFF', actorId: staff.id, staffId: staff.id,
      action: 'DOCUMENT_EXPORT', entity: 'Export', entityId: input.fileName,
      afterJson: { fileName, format: 'xlsx', sheets: input.sheets.map((s) => ({ name: s.name, rows: s.rows.length })) },
    });
    return { fileName, mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', buffer };
  }

  /**
   * Direct, unpersisted export for a document the officer is already viewing
   * (evidence bundle / tax report "Export to Excel"), as opposed to `generate`,
   * which is the IRIS chat flow — it persists an encrypted copy so the model's
   * answer can point the officer at a download link later. A file the officer
   * requested directly doesn't need that round-trip; still audited the same way.
   */
  async renderDirect(
    staff: { id: string; email?: string | null; firstName?: string | null; lastName?: string | null },
    spec: ReportSpec,
  ): Promise<{ fileName: string; mimeType: string; buffer: Buffer }> {
    const tenant = await this.prisma.tenant.findFirst({ select: { shortName: true } });
    const watermark = {
      orgShort: tenant?.shortName || 'IRS',
      officerName: [staff.firstName, staff.lastName].filter(Boolean).join(' ') || staff.email || staff.id,
    };
    const { buffer, mimeType, ext } = await this.render(spec, watermark);
    const fileName = `${spec.fileName}.${ext}`;
    await this.audit.log({
      actorType: 'STAFF', actorId: staff.id, staffId: staff.id,
      action: 'DOCUMENT_EXPORT', entity: 'Export', entityId: spec.fileName,
      afterJson: { fileName, format: spec.format, rows: spec.rows.length },
    });
    return { fileName, mimeType, buffer };
  }

  async download(exportId: string, staff: User): Promise<{ fileName: string; mimeType: string; buffer: Buffer }> {
    const row = await this.prisma.irisExport.findUnique({ where: { id: exportId } });
    if (!row) throw new NotFoundException('Export not found.');
    if (row.staffId !== staff.id) throw new ForbiddenException('This export belongs to another officer.');
    const b64 = this.crypto.decrypt(row.cipher);
    if (!b64) throw new Error('Failed to decrypt export.');
    await this.prisma.irisExport.update({ where: { id: exportId }, data: { downloadedAt: new Date() } });
    await this.audit.log({
      actorType: 'STAFF', actorId: staff.id, staffId: staff.id,
      action: 'IRIS_EXPORT_DOWNLOAD', entity: 'IrisExport', entityId: exportId,
    });
    return { fileName: row.fileName, mimeType: row.mimeType, buffer: Buffer.from(b64, 'base64') };
  }
}
